Models/Contacto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Formularios.Models
{
    public class Contacto
    {   
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set; }

        [Required (ErrorMessage = "El campo Nombres es obligatorio")]
        [StringLength (100, ErrorMessage = "El campo no puede tener mas de 100 caracteres")]
        [Column("Nombres"), ]
        public string Name { get; set; }

        [Required]
        [StringLength (150, ErrorMessage = "El campo Apellidos no puede tener mas de 150 caracteres")]
        [Column("Apellidos")]
        public string LastName { get; set; }

        [Required (ErrorMessage = " El campo Correo es requerido")]
        [EmailAddress (ErrorMessage = "El formato del correo electrónico es inválido")]
        [Column("Correo")]
        public string Email { get; set; }
        
        [StringLength (9, ErrorMessage = "El campo Teléfono no puede exceder los 9 caracteres")]
        [Column("Telefono")]
        public string? Phone { get; set; }

        [Column("Genero")]
        public string? Gender { get; set; }

        [Column("Ocupacion")]
        public string? Ocupation { get; set; }

        [Required (ErrorMessage = " El campo Comentario es requerido")]
        [StringLength (300, ErrorMessage = "El campo Comentario no puede exceder los 300 caracteres")]
        [Column("Comentario")]
        public string Comment { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace Formularios.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/ContactoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Formularios.DataAccess;
using Formularios.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Formularios.Controllers
{
    public class ContactoController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ContactoController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var contactos = _context.contactos.ToList();
            return View(contactos);
        }

        public IActionResult CreateContacto()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateContacto(Contacto contacto)
        {   
            if(!ModelState.IsValid)
            {
                foreach (var entry in ModelState)
                {
                    var fieldName = entry.Key;  // Nombre del campo que falló la validación
                    var state = entry.Value;
                    // Recorre todos los errores asociados a ese campo
                    foreach (var error in state.Errors)
                    {
                        var errorMessage = error.ErrorMessage;  // Mensaje de error que describe qué falló
                        Console.WriteLine($"Error en el campo {fieldName}: {errorMessage}");
                    }
                }
                Console.WriteLine("--------------");
                return View(contacto);  
            }
            _context.contactos.Add(contacto);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Formularios.Models;

namespace Formularios.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Contacto/CreateContacto.cshtml
@model Contacto
@{
    ViewData["Title"] = "Creación de Contacto";
}
<div class="container">
    <div class="row">
        <div class="col-6">
            <h1 class="text-center">@ViewData["Title"]</h1>
            <form method="post">
                <div class="form-group" asp-controller="Contacto" asp-action="CreateContacto">
                    <label asp-for="Name">Nombres:</label>
                    <input asp-for="Name" class="form-control" autofocus />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName">Apellidos:</label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email">Correo:</label>
                    <input asp-for="Email" class="form-control" placeholder="ejemplo@ejemplo.com" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Phone">Telefono:</label>
                    <input asp-for="Phone" class="form-control" placeholder="987654321" maxlength="9" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <p>Género:</p>
                    <input type="radio" asp-for="Gender" value="Masculino"/>
                    <label asp-for="Gender">Masculino:</label>
                    <input type="radio" asp-for="Gender" value="Femenino"/>
                    <label asp-for="Gender">Femenino:</label>
                </div>
                <div class="form-group">
                    <label asp-for="Ocupation">Ocupación:</label>
                    <select asp-for="Ocupation">
                        <option value="">--Elige una opción--</option>
                        <option value="Estudiante">Estudiante</option>
                        <option value="Egresado">Egresado</option>
                        <option value="Técnico">Técnico</option>
                        <option value="Docente">Docente</option>
                        <option value="Empresario">Empresario</option>
                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="Comment">Mensaje:</label>
                    <textarea asp-for="Comment" class="form-control"></textarea>
                    <span asp-validation-for="Comment" class="text-danger"></span>
                </div>
                <br>
                <div class="form-group">
                    <button class="btn btn-primary">Crear</button>
                </div>
            </form>
        </div>
        <div class="col-6">

        </div>
    </div>
</div>

Views/Contacto/Index.cshtml
@model List<Contacto>
@{
    ViewData["Title"] = "Lista de Contactos";
}

<div>
    <h1 class="display-5"><b>@ViewData["Title"]</b></h1>
    <a href="@Url.Action("CreateContacto", "Contacto")" class="btn btn-primary">Crear Contacto</a>
</div>
<br>
<div class="text-center">
    @if(Model.Count == 0)
    {
        <div class="alert alert-warning">
            <p class="">No hay contactos aún</p>
        </div>
    } else 
    
    {
        <table class="table" style="width: 80%;">
            <thead>
                <tr>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Correo</th>
                    <th>Teléfono</th>
                    <th>Género</th>
                    <th>Ocupación</th>
                    <th>Mensaje</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.LastName</td>
                        <td>@item.Email</td>
                        <td>@item.Phone</td>
                        <td>@item.Gender</td>
                        <td>@item.Ocupation</td>
                        <td>@item.Comment</td>
                    </tr>
                }  
            </tbody>
        </table>
    } 
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4"><b>Práctica</b></h1>
    <p>Prueba de ingreso de datos de contacto y muestra en una lista.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Formularios</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Formularios.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Formularios</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Index">Contactos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="CreateContacto">Crear Contacto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Formularios - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>